"""empty message

Revision ID: 44b71a12727f
Revises: da85b4d9adb0
Create Date: 2018-11-23 10:47:53.334833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44b71a12727f'
down_revision = 'da85b4d9adb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.Integer(), nullable=True))
    op.drop_index('pel', table_name='user')
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'pel')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pel', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('pel', 'user', ['pel'], unique=True)
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
