"""empty message

Revision ID: 6ec2795cdff4
Revises: 2960c4c2b67b
Create Date: 2018-11-23 09:50:40.648413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ec2795cdff4'
down_revision = '2960c4c2b67b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banners',
    sa.Column('bannerid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('bannerid')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('bannerid', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('image', mysql.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('bannerid'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('banners')
    # ### end Alembic commands ###
