"""empty message

Revision ID: da85b4d9adb0
Revises: 88c2218762b3
Create Date: 2018-11-23 10:42:08.472567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da85b4d9adb0'
down_revision = '88c2218762b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('duration', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'duration')
    # ### end Alembic commands ###
